###########
# site.url, site.title
title: Kosmos Mobile
url: "https://kosmomobile.com"

########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded



exclude: [
  'Gemfile',
  'Gemfile.lock',
  'Rakefile',
  'README.md',
  'node_modules',
  'vendor',
  'bower.json',
  'package.json',
  'gruntfile.js',
  'CONTRIBUTING.md',
  'components'
  ]

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

